#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),zlib=require('zlib');
const APP=__dirname,ROOT=path.resolve(process.argv[2]||path.join(APP,'..')),OUT=path.join(APP,'index.json');
const SUP=path.join(APP,'visual_supplements.json'),VISUAL=[path.join(APP,'part2_visual'),path.join(APP,'app','part2_visual')];
let supplements={};try{supplements=JSON.parse(fs.readFileSync(SUP,'utf8'))}catch{}
const flatten=x=>x==null?'':Array.isArray(x)?x.map(flatten).join('; '):typeof x==='object'?Object.entries(x).map(([k,v])=>k+': '+flatten(v)).join('; '):String(x);
const clean=s=>flatten(s).replace(/\s+/g,' ').trim().slice(0,120000);
const relative=(root,file)=>path.relative(root,file).replace(/\\/g,'/').normalize('NFC');
const key=s=>String(s||'').replace(/\\/g,'/').replace(/^\.\//,'').normalize('NFC').toLocaleLowerCase();
const walk=(d,a=[])=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){if(e.name==='node_modules'||e.name==='.git')continue;const p=path.join(d,e.name);if(e.isDirectory())walk(p,a);else if(/\.(pdf|pptx)$/i.test(e.name))a.push(p)}return a.sort()};
const zip=file=>{const b=fs.readFileSync(file),e=b.lastIndexOf(Buffer.from('PK\x05\x06'));let n=b.readUInt16LE(e+10),p=b.readUInt32LE(e+16),o=new Map;while(n--){const m=b.readUInt16LE(p+10),z=b.readUInt32LE(p+20),nl=b.readUInt16LE(p+28),el=b.readUInt16LE(p+30),cl=b.readUInt16LE(p+32),l=b.readUInt32LE(p+42),ln=b.readUInt16LE(l+26),le=b.readUInt16LE(l+28),r=b.subarray(l+30+ln+le,l+30+ln+le+z);o.set(b.subarray(p+46,p+46+nl).toString(),m?zlib.inflateRawSync(r):r);p+=46+nl+el+cl}return o};
const pptx=file=>{const z=zip(file),ns=[...z].filter(([n])=>/^ppt\/slides\/slide\d+\.xml$/i.test(n)).sort((a,b)=>+a[0].match(/\d+/)[0]-+b[0].match(/\d+/)[0]);return ns.map(([n],i)=>({number:i+1,slideText:clean(z.get(n).toString().replace(/<a:br\s*\/?>|<\/a:p>/gi,'\n').replace(/<a:t[^>]*>(.*?)<\/a:t>/gi,'$1').replace(/<[^>]+>/g,' '))}))};
const annotationText=a=>{const parts=[a.contentsObj?.str,a.contents,a.richText?.str,a.titleObj?.str,a.title].map(clean).filter(Boolean);return [...new Set(parts)].join(' — ')};
let pj;async function pdf(file){pj||=(pj=import('pdfjs-dist/legacy/build/pdf.mjs'));const {getDocument}=await pj,d=await getDocument({data:new Uint8Array(fs.readFileSync(file)),disableWorker:true,useWorkerFetch:false,isEvalSupported:false,verbosity:0}).promise,a=[];try{for(let i=1;i<=d.numPages;i++){const page=await d.getPage(i),c=await page.getTextContent(),slideText=clean(c.items.map(x=>x.str).join(' ')),annotations=(await page.getAnnotations({intent:'display'})).map(annotationText).filter(Boolean);a.push({number:i,slideText,annotations})}}finally{await d.cleanup()}return a}
function loadVisualReviews(dirs=VISUAL){const docs=new Map,warnings=[];for(const dir of Array.isArray(dirs)?dirs:[dirs]){if(!fs.existsSync(dir))continue;for(const name of fs.readdirSync(dir).filter(x=>x.endsWith('.json')).sort()){const location=path.join(dir,name);try{const doc=JSON.parse(fs.readFileSync(location,'utf8')),source=key(doc.sourceRelativePath);if(!source||!Array.isArray(doc.pages))throw Error('sourceRelativePath and pages are required');if(docs.has(source))throw Error('duplicate sourceRelativePath: '+doc.sourceRelativePath+' in '+docs.get(source).reviewFile);docs.set(source,{...doc,reviewFile:location})}catch(e){warnings.push('Visual review '+location+': '+e.message)}}}return{docs,warnings}}
const fields=['slideTextSummary','visualDescription','notes','interpretation','keywords','uncertainties'];
function applyVisualReview(pages,doc,warnings,label){const entries=new Map,validCount=pages.length;for(const raw of doc.pages){const n=Number(raw?.number);if(!Number.isInteger(n)||n<1||n>validCount){warnings.push(label+': out-of-range review page '+String(raw?.number));continue}if(entries.has(n)){warnings.push(label+': duplicate review page '+n);continue}entries.set(n,raw)}
  if(doc.pageCount!==validCount)warnings.push(label+': review pageCount '+doc.pageCount+' differs from PDF page count '+validCount);
  const declaredList=Array.isArray(doc.reviewedPages)?doc.reviewedPages.map(Number):null;
  const declared=declaredList?declaredList.length:Number(doc.reviewedPages);
  const declaredValid=declaredList?declaredList.length===entries.size&&new Set(declaredList).size===entries.size&&declaredList.every(n=>entries.has(n)):Number.isInteger(declared)&&declared===entries.size;
  if(!declaredValid)warnings.push(label+': reviewedPages does not match supplied page entries');
  let complete=0;for(const pg of pages){const raw=entries.get(pg.number);if(!raw){warnings.push(label+': missing review page '+pg.number);pg.visualReviewStatus='missing';continue}const reviewed=raw.visualReviewed===true,content=fields.some(f=>clean(raw[f]));if(!reviewed||!content){warnings.push(label+': incomplete review page '+pg.number);pg.visualReviewStatus='incomplete'}else{pg.visualReviewStatus='reviewed';complete++}for(const f of fields)pg[f]=clean(raw[f]);pg.visualReviewSource=doc.reviewFile}
  return{reviewedPages:complete,pageCount:validCount,complete:complete===validCount&&doc.pageCount===validCount&&declaredValid&&entries.size===validCount}}
const labelText=(label,value)=>{const s=clean(value);return s?label+': '+s:''};
function composePage(pg,extra){pg.legacySupplement=clean(extra);pg.text=[labelText('SLIDE TEXT',pg.slideText),labelText('PDF ANNOTATIONS',pg.annotations),labelText('VISUAL SUPPLEMENT',pg.legacySupplement),labelText('SLIDE TEXT SUMMARY',pg.slideTextSummary),labelText('VISUAL DESCRIPTION',pg.visualDescription),labelText('USER NOTES',pg.notes),labelText('INTERPRETATION',pg.interpretation),labelText('KEYWORDS',pg.keywords),labelText('UNCERTAINTIES',pg.uncertainties)].filter(Boolean).join('\n');return pg}
async function build(root=ROOT,{supplementData=supplements,visualDir=VISUAL,pdfReader=pdf,pptxReader=pptx}={}){const files=[],warnings=[],reviews=loadVisualReviews(visualDir),seen=new Set;warnings.push(...reviews.warnings);for(const p of walk(root))try{const rel=relative(root,p),k=path.extname(p).slice(1).toUpperCase(),pages=k==='PDF'?await pdfReader(p):pptxReader(p),review=reviews.docs.get(key(rel)),annotated=rel.split('/').includes('笔记版课件');if(review)seen.add(key(rel));const extra=annotated?{}:(supplementData[path.basename(p)]||{});let visualReview;if(review)visualReview=applyVisualReview(pages,review,warnings,rel);else if(annotated&&/^2\.[0-3]/.test(path.basename(p)))warnings.push(rel+': missing visual review document');for(const pg of pages)composePage(pg,extra[pg.number]);files.push({path:p,relativePath:rel,name:path.basename(p),kind:k,size:fs.statSync(p).size,mtimeMs:fs.statSync(p).mtimeMs,variant:annotated?'annotated':'original',canonicalRelativePath:path.basename(p),visualReview,pages})}catch(e){warnings.push(relative(root,p)+': '+e.message)}for(const [source,doc] of reviews.docs)if(!seen.has(source))warnings.push('Visual review '+path.basename(doc.reviewFile)+': source not found: '+doc.sourceRelativePath);return{version:4,folder:root,generatedAt:new Date().toISOString(),files,warnings}}
async function main(){fs.writeFileSync(OUT,JSON.stringify(await build()))}
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1});
module.exports={build,loadVisualReviews,applyVisualReview,composePage,annotationText,relative,key,pdf};
